# TensorFlow Tutorial  
https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2

Tensor is a multi-dimentional array that has the ability to run on gpu. From mathematical perspective Tensor is a generalization of scalar vector and matrix. for example; a vector is a one dimentional Tensor and matrix is a two dimentional Tensor

In [ ]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf

## Initialization of Tensors

In [ ]:
x=tf.constant(4)
print(x)

#we can also specify the shape
x=tf.constant(4, shape=(1,1))
print(f"\nshape of (1,1) is \n",x)

x=tf.constant(4, shape=(1,2))
print(f"\nshape of (1,2) is \n", x)

x=tf.constant(4, shape=(2,1))
print(f"\nshape of (2,1) is \n", x)

# we can also specify dtype
x=tf.constant(4, shape=(1,2), dtype=tf.float32)
print(f"\nshape of (1,2) and dtype of float32 is \n", x)

x=tf.constant([[1,2,3],[4,5,6]])
print(f"\n",x)

x=tf.random.normal((3,3), mean=0,stddev=1)
print(f"\n normal distribution with mean and standard deviation\n", x)

x=tf.range(start=1, limit=50, delta=5)
print(f"\n",x)



tf.Tensor(4, shape=(), dtype=int32)

shape of (1,1) is 
 tf.Tensor([[4]], shape=(1, 1), dtype=int32)

shape of (1,2) is 
 tf.Tensor([[4 4]], shape=(1, 2), dtype=int32)

shape of (2,1) is 
 tf.Tensor(
[[4]
 [4]], shape=(2, 1), dtype=int32)

shape of (1,2) and dtype of float32 is 
 tf.Tensor([[4. 4.]], shape=(1, 2), dtype=float32)

 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

 normal distribution with mean and standard deviation
 tf.Tensor(
[[ 0.28107783  1.5313665  -0.07678747]
 [-0.52961093  0.9669891  -2.0312605 ]
 [-0.39125445 -1.1514721  -0.41348538]], shape=(3, 3), dtype=float32)

 tf.Tensor([ 1  6 11 16 21 26 31 36 41 46], shape=(10,), dtype=int32)


## Mathematical Operation

In [ ]:
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])
z=tf.add(x,y) #same as z=x+y, this will also work
print(z)

x=tf.random.normal((2,3))
y=tf.random.normal((3,4))

z=tf.matmul(x,y) #matrix multiplication
print(f"\n",z)
z=x@y #matrix multiplication


tf.Tensor([5 7 9], shape=(3,), dtype=int32)

 tf.Tensor(
[[-0.70304227  1.503948   -1.5575938  -1.7628423 ]
 [-0.18627337 -0.7646644  -0.79268235 -0.14368856]], shape=(2, 4), dtype=float32)


## Reshaping

In [ ]:
x=tf.range(9)
print(f"\n",x)

x=tf.reshape(x, (3,3))
print(f"\n",x)


 tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)

 tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


## Neural Network with sequentional and funtional API

* keras : Keras is a high-level API for building and training deep learning models, and it is integrated into TensorFlow. It was originally developed as an independent library but has been incorporated into TensorFlow since version 2.0. It provides a high-level, user-friendly API that makes it easy to build and train models with just a few lines of code.

In [ ]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist #import dataset

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
#print(x_train)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

# we need to flaten them so that we have one column
'''
-1 indicates keep whatever the value is in the dimention
we want data as float
these are going to be numpy array cz these are automatically done by tensorflow
'''
x_train = x_train.reshape(-1, 28 * 28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28 * 28).astype("float32") / 255.0
print(f"after flaten the list is like\n", x_train)
print(f"\nafter flaten the shape is like\n", x_train.shape)



11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)
after flaten the list is like
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

after flaten the shape is like
 (60000, 784)


In [ ]:
# Sequential API (Very convenient, not very flexible)

model = keras.Sequential(
    [
        keras.Input(shape=(28 * 28)),
        layers.Dense(512, activation="relu"),
        layers.Dense(256, activation="relu"),
        layers.Dense(10),
    ]
)

In [ ]:
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation="relu"))
model.add(layers.Dense(256, activation="relu", name="my_layer"))
model.add(layers.Dense(10))


In [ ]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

Epoch 1/5
1875/1875 - 17s - loss: 2.3061 - accuracy: 0.2411 - 17s/epoch - 9ms/step
Epoch 2/5
1875/1875 - 17s - loss: 2.3025 - accuracy: 0.1946 - 17s/epoch - 9ms/step
Epoch 3/5
1875/1875 - 16s - loss: 2.3025 - accuracy: 0.1936 - 16s/epoch - 8ms/step
Epoch 4/5
1875/1875 - 17s - loss: 2.3025 - accuracy: 0.1933 - 17s/epoch - 9ms/step
Epoch 5/5
1875/1875 - 16s - loss: 2.3025 - accuracy: 0.1927 - 16s/epoch - 9ms/step
313/313 - 1s - loss: 2.3026 - accuracy: 0.1887 - 1s/epoch - 3ms/step


[2.30259108543396, 0.18870000541210175]